---
# schedule only one pod with the same lable into one node
# one single replica run in one node
# kubectl get pods -o wide           
# NAME                                                     READY   STATUS    RESTARTS   AGE   IP             NODE                NOMINATED NODE   READINESS GATES
# my-http-server-pod-anti-affinity-hard-54f65996c9-cnjzm   1/1     Running   0          29s   10.244.0.246   kubernetes-master   <none>           <none>
# my-http-server-pod-anti-affinity-hard-54f65996c9-wv2q4   1/1     Running   0          29s   10.244.1.11    kubernetes-worker   <none>           <none>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-http-server-pod-anti-affinity-hard
  labels:
    name: my-http-server-pod-anti-affinity-hard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-http-server-pod-anti-affinity-hard
  template:
    metadata:
      labels:
        app: my-http-server-pod-anti-affinity-hard
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app 
                    operator: In 
                    values:
                      - my-http-server-pod-anti-affinity-hard
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image:  nginx
        name:  my-http-server-node-affinity-hard
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort:  80
          name:  http-server
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}