apiVersion: batch/v1
kind: CronJob
metadata:
  name: simplejob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simplejob
            image: simplejob:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure