apiVersion: v1
kind: ServiceAccount
metadata:
  name: run-python-jobs
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: run-python-jobs-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-python-jobs-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: run-python-jobs
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: run-python-jobs-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name:  my-python-program
spec:
  template:
    metadata:
      name:  name
      namespace: default
    spec:
      serviceAccountName: run-python-jobs
      containers:
        - name: my-python-program
          image: python:3.7
          command: ['python', '-c', 'print("hello .......")']
      restartPolicy: Never
  backoffLimit: 4