apiVersion: apps/v1
kind: Replicaset
metadata:
  name: myapp-replica-set
  labels:
    app: myapp
    type: webserver
spec:
  template:
    metadata:
      name : nginx-pod
      labels:
        app: server
        type: backend
    spec:
      containers:
        - name : nginx-server
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: webserver