apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: webserver
spec:
  template:
    metadata:
      name : nginx-pod
      labels:
        app: server
        type: backend
    spec:
      containers:
        - name : nginx-server
          image: nginx
  replicas: 3