apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: osama
spec:
  groups:
    - system:authenticated
  usages:
    - digital signture
    - key encipherment
    - server auth
  signerName: kubernetes.io/kube-apiserver-client
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZiM05oYldFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFEV1V5TUJ0V3FhVEhYa3g5UmFJTU5CYmlvZzFDOFU1WnB5cFU3OUYvbTVxY0kxCkhvajl1Y09IdE9vQndFQkJaZWVaWEFFMktTT2tzc2M1SEJzU1VaY2pUQnBwM0p1OS9VYllQQU9yUHlwaFpkbDEKcmJXRG5zeWRTaGhvVko3dFF4VGpPTDJneGErdHJBM0dRbHE4eUZCcUdkRXpzcU1pQnlyZ1dVdmJzemo3SnBIdQprWlBHQUVGOGpCR1JwS0xsVzI1eXVuU3cwTEV2TExFa3Bhek50STc5eStHdjF2SDFmNXBZVmxXMGVhMU9wUHVwCnREa205QmVHNXNLaVkxMGhlaUxLMUVvb2dtSGlKbWFwYkp4T2NIbzNtMGFZdGVuZk1FV2x6Vi9wRlJmUDlScTQKdmE1MjNNZndZMTNuZ2JyN21ENURIRkdFeTNTSjNUUWN0ZDdPV1Y5VkFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFnd0ZzUkNtam51N0hVYTFucVJIYjlRMEFoRFl5Zi9FQkpjRVFYWHVPVENmeGVMS3B1YWhaCnZZVjhVLzhkUFVtSENHMXBMRThleHpScnhJVVhZOTk1TlU2ZGh3MFpIRW1jejZFNE1kRmExQldIYTlrUWE3UTcKVkNRSll4R0NyQnpGZHE1OHR0Tlp0N2V2VGVUQzRvZWl6MUZFN0VuVjlmakN4UnJBMTR5cnZRLzVrZDFqV0pLNgo1OGIrYmtZRUdtaEExZVNaZjUxdTNrZnAzWHY5QkhMMm9SZ3llemI2eGNsdmV3WUtqemREY1NoVkZUQi9kaDYzCkVMR2NWeVlPdnV1d3dwMHRoUFZNbTY1cjZ1ZWdQcGlJNWwwZEhrSjFKSTBwZnpldm9HTVlzQjNHNXlpVVdtUkEKNFNKL1ozZytvb0RkcWUxRE5hUkpsOTB3dE1wRXpJK3ZOUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=