apiVersion: v1
kind: Config
current-context: my-kube-admin@my-kube-playground
clusters:
  - name : my-kube-playground
    cluster:
      certificate-authority: ca.crt
      server: https://my-kube-playground:6443

contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
      # namespace : hr
users:
  - name : my-kube-admin
    user:
      client-certificate: admin.crt
      client-key: admin.key
# kubectl config view
# kubectl config use-context my-kube-admin@my-kube-playground