apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemon-set
  labels:
    app: myapp
    type: webserver
spec:
  template:
    metadata:
      name : nginx-pod
      labels:
        app: server
        type: backend
    spec:
      containers:
        - name : nginx-server
          image: nginx
  selector:
    matchLabels:
      type: webserver