apiVersion: v1
kind: Pod
metadata:
  name: livenessProbe
spec:
  containers:
    - name: livenessProbe
      image: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
