# kubectl create secret generic secret-name --from-literal=password=osama
# kubectl create secret generic secrete-name --from-file=
apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
data:
  DB_PASSWORD: cGFzc3dvcmQK #  echo "password" | base64